#!/usr/bin/env bash
set -euo pipefail

# setup_android_sdk_ndk.sh
# Installs Android SDK command-line tools, NDK r27+, CMake for deterministic builds
# Compatible with Ubuntu 20.04+ / macOS / Fedora

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Configuration
SDK_VERSION="11076708"  # Latest cmdline-tools
NDK_VERSION="27.0.12077973"
CMAKE_VERSION="3.22.1"
PLATFORM_VERSION="34"
BUILD_TOOLS_VERSION="34.0.0"

ANDROID_HOME="${ANDROID_HOME:-${HOME}/Android/Sdk}"
JAVA_HOME="${JAVA_HOME:-$(command -v java | xargs dirname | xargs dirname 2>/dev/null || echo '')}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# Verify prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    if ! command -v java &>/dev/null; then
        log_error "Java not found. Install OpenJDK 17+ (apt install openjdk-17-jdk)"
    fi
    
    local java_version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)
    if [[ "$java_version" -lt 17 ]]; then
        log_warn "Java $java_version detected. Java 17+ recommended for NDK r27+"
    fi
    
    if ! command -v unzip &>/dev/null; then
        log_error "unzip not found. Install via package manager."
    fi
    
    log_info "Prerequisites satisfied (Java $java_version, unzip available)"
}

# Download SDK command-line tools
install_sdk_tools() {
    log_info "Installing Android SDK command-line tools..."
    
    mkdir -p "$ANDROID_HOME"
    
    local os_type=""
    case "$(uname -s)" in
        Linux*) os_type="linux" ;;
        Darwin*) os_type="mac" ;;
        *) log_error "Unsupported OS: $(uname -s)" ;;
    esac
    
    local sdk_url="https://dl.google.com/android/repository/commandlinetools-${os_type}-${SDK_VERSION}_latest.zip"
    local temp_zip="/tmp/cmdline-tools.zip"
    
    if [[ ! -d "$ANDROID_HOME/cmdline-tools/latest" ]]; then
        log_info "Downloading SDK tools from $sdk_url"
        curl -fL -o "$temp_zip" "$sdk_url" || log_error "Download failed"
        
        unzip -q "$temp_zip" -d "$ANDROID_HOME/cmdline-tools"
        mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
        rm "$temp_zip"
        
        log_info "SDK tools installed to $ANDROID_HOME/cmdline-tools/latest"
    else
        log_info "SDK tools already installed"
    fi
    
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
}

# Accept licenses and install NDK + CMake
install_ndk_cmake() {
    log_info "Accepting licenses and installing NDK $NDK_VERSION + CMake $CMAKE_VERSION..."
    
    yes | sdkmanager --licenses >/dev/null 2>&1 || true
    
    sdkmanager \
        "ndk;$NDK_VERSION" \
        "cmake;$CMAKE_VERSION" \
        "platform-tools" \
        "platforms;android-$PLATFORM_VERSION" \
        "build-tools;$BUILD_TOOLS_VERSION" \
        "extras;google;google_play_services" \
        "extras;android;m2repository" || log_error "sdkmanager installation failed"
    
    log_info "NDK installed: $ANDROID_HOME/ndk/$NDK_VERSION"
    log_info "CMake installed: $ANDROID_HOME/cmake/$CMAKE_VERSION"
}

# Create environment config
write_env_file() {
    local env_file="$PROJECT_ROOT/local.properties"
    
    log_info "Writing environment to $env_file"
    
    cat > "$env_file" <<EOF
# Auto-generated by setup_android_sdk_ndk.sh
sdk.dir=$ANDROID_HOME
ndk.dir=$ANDROID_HOME/ndk/$NDK_VERSION
cmake.dir=$ANDROID_HOME/cmake/$CMAKE_VERSION
EOF
    
    log_info "Environment configuration:"
    cat "$env_file"
}

# Verify installation
verify_installation() {
    log_info "Verifying installation..."
    
    local ndk_path="$ANDROID_HOME/ndk/$NDK_VERSION"
    local cmake_path="$ANDROID_HOME/cmake/$CMAKE_VERSION/bin/cmake"
    
    if [[ ! -d "$ndk_path" ]]; then
        log_error "NDK not found at $ndk_path"
    fi
    
    if [[ ! -x "$cmake_path" ]]; then
        log_error "CMake not found at $cmake_path"
    fi
    
    log_info "✓ NDK version: $(cat "$ndk_path/source.properties" | grep Pkg.Revision | cut -d'=' -f2)"
    log_info "✓ CMake version: $("$cmake_path" --version | head -n1)"
    log_info "✓ Platform tools: $(adb --version | head -n1)"
}

# Main execution
main() {
    log_info "Starting Android SDK/NDK setup for Cortex-N project..."
    
    check_prerequisites
    install_sdk_tools
    install_ndk_cmake
    write_env_file
    verify_installation
    
    log_info "✓ Setup complete! Add these to your shell profile:"
    echo "export ANDROID_HOME=$ANDROID_HOME"
    echo "export PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$PATH"
    echo "export PATH=\$ANDROID_HOME/platform-tools:\$PATH"
}

main "$@"
